---
kind: pipeline
type: docker
name: otp-deploy

clone:
  disable: true

steps:
- name: slb-before-api01
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api01-before.sh
  when:
    ref:
      - refs/tags/api01-otp-*
      - refs/tags/api01-test-*

- name: slb-before-api02
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api02-before.sh
  when:
    ref:
      - refs/tags/api02-otp-*
      - refs/tags/api02-test-*

- name: docker-otp-api01
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api01-host
    username: 
      from_secret: api01-user
    password:
      from_secret: api01-pwd
    port:
      from_secret: api01-port
    command_timeout: 180m
    script:
      - cd /root/thunderfire_otp
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi opt_rpc:latest
      - docker rmi opt_api:latest
      - docker image prune -f
      - DOCKER_BUILDKIT=1 docker build -t otp_rpc -f rpc/Dockerfile .
      - DOCKER_BUILDKIT=1 docker build -t otp_api -f api/Dockerfile .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api01-otp-*
      - refs/tags/api01-test-*
    status:
      - success

- name: docker-otp-api02
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api02-host
    username: 
      from_secret: api02-user
    password:
      from_secret: api02-pwd
    port:
      from_secret: api02-port
    command_timeout: 180m
    script:
      - cd /root/thunderfire_otp
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi opt_rpc:latest
      - docker rmi opt_api:latest
      - docker image prune -f
      - DOCKER_BUILDKIT=1 docker build -t otp_rpc -f rpc/Dockerfile .
      - DOCKER_BUILDKIT=1 docker build -t otp_api -f api/Dockerfile .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api02-otp-*
      - refs/tags/api02-test-*
    status:
      - success

- name: slb-after
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: elk-host
    username: 
      from_secret: elk-user
    password:
      from_secret: elk-pwd
    port:
      from_secret: elk-port
    command_timeout: 180m
    script:
      - cd /home/aliyun_deploy
      - ./api-after.sh
  when:
    ref:
      - refs/tags/api01-otp-*
      - refs/tags/api02-otp-*
      - refs/tags/api-bal*
