---
kind: pipeline
type: docker
name: otp-deploy

clone:
  disable: true

steps:
- name: docker-otp-api01
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api01-host
    username: 
      from_secret: api01-user
    password:
      from_secret: api01-pwd
    port:
      from_secret: api01-port
    command_timeout: 180m
    script:
      - cd /root/thunderfire_otp
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi opt_rpc:latest
      - docker rmi opt_api:latest
      - docker image prune -f
      - DOCKER_BUILDKIT=1 docker build -t otp_rpc -f rpc/Dockerfile .
      - DOCKER_BUILDKIT=1 docker build -t otp_api -f api/Dockerfile .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api01-otp-*
    status:
      - success

- name: docker-otp-api02
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: api02-host
    username: 
      from_secret: api02-user
    password:
      from_secret: api02-pwd
    port:
      from_secret: api02-port
    command_timeout: 180m
    script:
      - cd /root/thunderfire_otp
      - git checkout -- .
      - git pull origin master
      - go mod tidy
      - docker-compose down
      - docker rmi opt_rpc:latest
      - docker rmi opt_api:latest
      - docker image prune -f
      - DOCKER_BUILDKIT=1 docker build -t otp_rpc -f rpc/Dockerfile .
      - DOCKER_BUILDKIT=1 docker build -t otp_api -f api/Dockerfile .
      - docker-compose up -d
  when:
    ref:
      - refs/tags/api02-otp-*
    status:
      - success