// Code generated by goctl. DO NOT EDIT.
package types

type OtpGenReq struct {
	Issuer  string `json:"issuer"`
	Account string `json:"account"`
}

type OtpGenReply struct {
	Code    string  `json:"code"`
	Message string  `json:"message"`
	Data    OtpData `json:"data,omitempty"`
}

type OtpData struct {
	Secret string `json:"secret"`
	Qrcode string `json:"qrcode"`
}

type OtpVaildReq struct {
	PassCode string `json:"passCode"`
	Secret   string `json:"secret"`
}

type OtpVaildReply struct {
	Vaild bool `json:"vaild"`
}
